from django.contrib.gis.db import models

settingCHOICES = (("open-air", "open-air"), ("cave", "cave"), ("rockshelter", "rockshelter"))
countryCHOICES = (
    ('United States of America', ('United States of America')),
    ('Afghanistan', ('Afghanistan')),
    ('Aland Islands', ('Aland Islands')),
    ('Albania', ('Albania')),
    ('Algeria', ('Algeria')),
    ('American Samoa', ('American Samoa')),
    ('Andorra', ('Andorra')),
    ('Angola', ('Angola')),
    ('Anguilla', ('Anguilla')),
    ('Antigua and Barbuda', ('Antigua and Barbuda')),
    ('Argentina', ('Argentina')),
    ('Armenia', ('Armenia')),
    ('Aruba', ('Aruba')),
    ('Australia', ('Australia')),
    ('Austria', ('Austria')),
    ('Azerbaijan', ('Azerbaijan')),
    ('Bahamas', ('Bahamas')),
    ('Bahrain', ('Bahrain')),
    ('Bangladesh', ('Bangladesh')),
    ('Barbados', ('Barbados')),
    ('Belarus', ('Belarus')),
    ('Belgium', ('Belgium')),
    ('Belize', ('Belize')),
    ('Benin', ('Benin')),
    ('Bermuda', ('Bermuda')),
    ('Bhutan', ('Bhutan')),
    ('Bolivia', ('Bolivia')),
    ('Bosnia and Herzegovina', ('Bosnia and Herzegovina')),
    ('Botswana', ('Botswana')),
    ('Brazil', ('Brazil')),
    ('British Virgin Islands', ('British Virgin Islands')),
    ('Brunei Darussalam', ('Brunei Darussalam')),
    ('Bulgaria', ('Bulgaria')),
    ('Burkina Faso', ('Burkina Faso')),
    ('Burundi', ('Burundi')),
    ('Cambodia', ('Cambodia')),
    ('Cameroon', ('Cameroon')),
    ('Canada', ('Canada')),
    ('Cape Verde', ('Cape Verde')),
    ('Cayman Islands', ('Cayman Islands')),
    ('Central African Republic', ('Central African Republic')),
    ('Chad', ('Chad')),
    ('Channel Islands', ('Channel Islands')),
    ('Chile', ('Chile')),
    ('China', ('China')),
    ('China - Hong Kong', ('China - Hong Kong')),
    ('China - Macao', ('China - Macao')),
    ('Colombia', ('Colombia')),
    ('Comoros', ('Comoros')),
    ('Congo', ('Congo')),
    ('Cook Islands', ('Cook Islands')),
    ('Costa Rica', ('Costa Rica')),
    ('Cote d\'Ivoire', ('Cote d\'Ivoire')),
    ('Croatia', ('Croatia')),
    ('Cuba', ('Cuba')),
    ('Cyprus', ('Cyprus')),
    ('Czech Republic', ('Czech Republic')),
    ('Democratic People\'s Republic of Korea', ('Democratic People\'s Republic of Korea')),
    ('Democratic Republic of the Congo', ('Democratic Republic of the Congo')),
    ('Denmark', ('Denmark')),
    ('Djibouti', ('Djibouti')),
    ('Dominica', ('Dominica')),
    ('Dominican Republic', ('Dominican Republic')),
    ('Ecuador', ('Ecuador')),
    ('Egypt', ('Egypt')),
    ('El Salvador', ('El Salvador')),
    ('Equatorial Guinea', ('Equatorial Guinea')),
    ('Eritrea', ('Eritrea')),
    ('Estonia', ('Estonia')),
    ('Ethiopia', ('Ethiopia')),
    ('Faeroe Islands', ('Faeroe Islands')),
    ('Falkland Islands (Malvinas)', ('Falkland Islands (Malvinas)')),
    ('Fiji', ('Fiji')),
    ('Finland', ('Finland')),
    ('France', ('France')),
    ('French Guiana', ('French Guiana')),
    ('French Polynesia', ('French Polynesia')),
    ('Gabon', ('Gabon')),
    ('Gambia', ('Gambia')),
    ('Georgia', ('Georgia')),
    ('Germany', ('Germany')),
    ('Ghana', ('Ghana')),
    ('Gibraltar', ('Gibraltar')),
    ('Greece', ('Greece')),
    ('Greenland', ('Greenland')),
    ('Grenada', ('Grenada')),
    ('Guadeloupe', ('Guadeloupe')),
    ('Guam', ('Guam')),
    ('Guatemala', ('Guatemala')),
    ('Guernsey', ('Guernsey')),
    ('Guinea', ('Guinea')),
    ('Guinea-Bissau', ('Guinea-Bissau')),
    ('Guyana', ('Guyana')),
    ('Haiti', ('Haiti')),
    ('Holy See (Vatican City)', ('Holy See (Vatican City)')),
    ('Honduras', ('Honduras')),
    ('Hungary', ('Hungary')),
    ('Iceland', ('Iceland')),
    ('India', ('India')),
    ('Indonesia', ('Indonesia')),
    ('Iran', ('Iran')),
    ('Iraq', ('Iraq')),
    ('Ireland', ('Ireland')),
    ('Isle of Man', ('Isle of Man')),
    ('Israel', ('Israel')),
    ('Italy', ('Italy')),
    ('Jamaica', ('Jamaica')),
    ('Japan', ('Japan')),
    ('Jersey', ('Jersey')),
    ('Jordan', ('Jordan')),
    ('Kazakhstan', ('Kazakhstan')),
    ('Kenya', ('Kenya')),
    ('Kiribati', ('Kiribati')),
    ('Kuwait', ('Kuwait')),
    ('Kyrgyzstan', ('Kyrgyzstan')),
    ('Lao People\'s Democratic Republic', ('Lao People\'s Democratic Republic')),
    ('Latvia', ('Latvia')),
    ('Lebanon', ('Lebanon')),
    ('Lesotho', ('Lesotho')),
    ('Liberia', ('Liberia')),
    ('Libyan Arab Jamahiriya', ('Libyan Arab Jamahiriya')),
    ('Liechtenstein', ('Liechtenstein')),
    ('Lithuania', ('Lithuania')),
    ('Luxembourg', ('Luxembourg')),
    ('Macedonia', ('Macedonia')),
    ('Madagascar', ('Madagascar')),
    ('Malawi', ('Malawi')),
    ('Malaysia', ('Malaysia')),
    ('Maldives', ('Maldives')),
    ('Mali', ('Mali')),
    ('Malta', ('Malta')),
    ('Marshall Islands', ('Marshall Islands')),
    ('Martinique', ('Martinique')),
    ('Mauritania', ('Mauritania')),
    ('Mauritius', ('Mauritius')),
    ('Mayotte', ('Mayotte')),
    ('Mexico', ('Mayotte')),
    ('Micronesia, Federated States of', ('Micronesia, Federated States of')),
    ('Monaco', ('Monaco')),
    ('Mongolia', ('Mongolia')),
    ('Montenegro', ('Montenegro')),
    ('Montserrat', ('Montserrat')),
    ('Morocco', ('Morocco')),
    ('Mozambique', ('Mozambique')),
    ('Myanmar', ('Myanmar')),
    ('Namibia', ('Namibia')),
    ('Nauru', ('Nauru')),
    ('Nepal', ('Nepal')),
    ('Netherlands', ('Netherlands')),
    ('Netherlands Antilles', ('Netherlands Antilles')),
    ('New Caledonia', ('New Caledonia')),
    ('New Zealand', ('New Zealand')),
    ('Nicaragua', ('Nicaragua')),
    ('Niger', ('Niger')),
    ('Nigeria', ('Nigeria')),
    ('Niue', ('Niue')),
    ('Norfolk Island', ('Norfolk Island')),
    ('Northern Mariana Islands', ('Northern Mariana Islands')),
    ('Norway', ('Norway')),
    ('Occupied Palestinian Territory', ('Occupied Palestinian Territory')),
    ('Oman', ('Oman')),
    ('Pakistan', ('Pakistan')),
    ('Palau', ('Palau')),
    ('Panama', ('Panama')),
    ('Papua New Guinea', ('Papua New Guinea')),
    ('Paraguay', ('Paraguay')),
    ('Peru', ('Peru')),
    ('Philippines', ('Philippines')),
    ('Pitcairn', ('Pitcairn')),
    ('Poland', ('Poland')),
    ('Portugal', ('Portugal')),
    ('Puerto Rico', ('Puerto Rico')),
    ('Qatar', ('Qatar')),
    ('Republic of Korea', ('Republic of Korea')),
    ('Republic of Moldova', ('Republic of Moldova')),
    ('Reunion', ('Reunion')),
    ('Romania', ('Romania')),
    ('Russian Federation', ('Russian Federation')),
    ('Rwanda', ('Rwanda')),
    ('Saint-Barthelemy', ('Saint-Barthelemy')),
    ('Saint Helena', ('Saint Helena')),
    ('Saint Kitts and Nevis', ('Saint Kitts and Nevis')),
    ('Saint Lucia', ('Saint Lucia')),
    ('Saint-Martin (French part)', ('Saint-Martin (French part)')),
    ('Saint Pierre and Miquelon', ('Saint Pierre and Miquelon')),
    ('Saint Vincent and the Grenadines', ('Saint Vincent and the Grenadines')),
    ('Samoa', ('Samoa')),
    ('San Marino', ('San Marino')),
    ('Sao Tome and Principe', ('Sao Tome and Principe')),
    ('Saudi Arabia', ('Saudi Arabia')),
    ('Senegal', ('Senegal')),
    ('Serbia', ('Serbia')),
    ('Seychelles', ('Seychelles')),
    ('Sierra Leone', ('Sierra Leone')),
    ('Singapore', ('Singapore')),
    ('Slovakia', ('Slovakia')),
    ('Slovenia', ('Slovenia')),
    ('Solomon Islands', ('Solomon Islands')),
    ('Somalia', ('Somalia')),
    ('South Africa', ('South Africa')),
    ('Spain', ('Spain')),
    ('Sri Lanka', ('Sri Lanka')),
    ('Sudan', ('Sudan')),
    ('Suriname', ('Suriname')),
    ('Svalbard and Jan Mayen Islands', ('Svalbard and Jan Mayen Islands')),
    ('Swaziland', ('Swaziland')),
    ('Sweden', ('Sweden')),
    ('Switzerland', ('Switzerland')),
    ('Syrian Arab Republic', ('Syrian Arab Republic')),
    ('Tajikistan', ('Tajikistan')),
    ('Thailand', ('Thailand')),
    ('Timor-Leste', ('Timor-Leste')),
    ('Togo', ('Togo')),
    ('Tokelau', ('Tokelau')),
    ('Tonga', ('Tonga')),
    ('Trinidad and Tobago', ('Trinidad and Tobago')),
    ('Tunisia', ('Tunisia')),
    ('Turkey', ('Turkey')),
    ('Turkmenistan', ('Turkmenistan')),
    ('Turks and Caicos Islands', ('Turks and Caicos Islands')),
    ('Tuvalu', ('Tuvalu')),
    ('Uganda', ('Uganda')),
    ('Ukraine', ('Ukraine')),
    ('United Arab Emirates', ('United Arab Emirates')),
    ('United Kingdom', ('United Kingdom')),
    ('United Republic of Tanzania', ('United Republic of Tanzania')),
    ('United States of America', ('United States of America')),
    ('United States Virgin Islands', ('United States Virgin Islands')),
    ('Uruguay', ('Uruguay')),
    ('Uzbekistan', ('Uzbekistan')),
    ('Vanuatu', ('Vanuatu')),
    ('Venezuela (Bolivarian Republic of)', ('Venezuela (Bolivarian Republic of)')),
    ('Viet Nam', ('Viet Nam')),
    ('Wallis and Futuna Islands', ('Wallis and Futuna Islands')),
    ('Western Sahara', ('Western Sahara')),
    ('Yemen', ('Yemen')),
    ('Zambia', ('Zambia')),
    ('Zimbabwe', ('Zimbabwe')),
)

regionCHOICES = (("southern_africa", "southern Africa"), ("eastern_africa", "eastern Africa"), ("northern_africa", "northern Africa"), ("", ""), ("", ""))
continentCHOICES = (("Africa", "Africa"), ("Europe", "Europe"), ("Asia", "Asia"), ("North America", "North America"), ("South America", "South America"), ("Australia", "Australia"), ("Antarctica", "Antarctica"))
materialCHOICES = (("basketry", "basketry"), ("building material", "building material"), ("ceramic", "ceramic"), ("chipped stone", "chipped stone"), ("dating sample", "dating sample"),
                   ("fauna", "fauna"), ("fire-cracked rock", "fire-cracked rock"), ("glass", "glass"), ("ground stone", "ground stone"), ("hide", "hide"), ("human remains", "human remains"),
                   ("macrobotanical", "macrobotanical"), ("metal", "metal"), ("mineral", "mineral"), ("pollen", "pollen"), ("shell", "shell"), ("textile", "textile"), ("wood", "wood")) #Choice list comes from tDAR"
epochCHOICES = (("Pliocene", "Pliocene"), ("Pleistocene", "Pleistocene"), ("Holocene", "Holocene"))


class PaleoSite(models.Model):
    """
    Namespaces
    dwc: Darwin Core
    dc: Dublin Core
    tdr: the Digital Archaeological Record tDAR
    """
    name = models.CharField(max_length=255, blank=False, null=False)  # REQUIRED
    setting = models.CharField(max_length=255, blank=True, null=True, choices=settingCHOICES)
    continent = models.CharField(max_length=255, blank=True, null=True, choices=continentCHOICES)  # dwc:continent
    country = models.CharField(max_length=255, blank=True, null=True, choices=countryCHOICES)  # dwc:country
    region = models.CharField(max_length=255, blank=True, null=True, choices=regionCHOICES)  # dwc:locality
    research_project = models.CharField(max_length=255, blank=True, null=True)  # e.g.
    collection_code = models.CharField(null=True, blank=True,max_length=20)  # dwc:collection_code
    geological_member = models.CharField(max_length=255, blank=True, null=True)  # dwd:member
    cultural_term = models.CharField(max_length=255, blank=True, null=True)  # tdr:cultural_term, Stillbay
    technology_period = models.CharField(max_length=255, blank=True, null=True)  # e.g. MSA, ESA, UP, MP
    start_date = models.CharField(max_length=255, blank=True, null=True)  # tdr: start_date
    end_date = models.CharField(max_length=255, blank=True, null=True)  # tdr:end_date
    geological_epoch = models.CharField(max_length=255, blank=True, null=True, choices=epochCHOICES)  # dwc:epoch
    date_description = models.CharField(max_length=255, blank=True, null=True)  # tdr:date_description, e.g. ESR, OSL
    material = geom = models.CharField(max_length=255, blank=True, null=True, choices=materialCHOICES)  # tdr:material_types
    references = models.TextField(null=True, blank=True,max_length=2500)  # dwc:references
    remarks = models.TextField(null=True, blank=True, max_length=2500)
    geom = models.PointField(srid=4326)


