from django.db import models

# Create your models here.
class Locality(models.Model):
    name = models.CharField(max_length=30, blank=True, null=True)
    type = models.CharField(max_length=1, blank=True, null=True)
    date_meth = models.CharField(max_length=9, blank=True, null=True)
    max_age = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    min_age = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    bfa_max = models.CharField(max_length=25, blank=True, null=True)
    bfa_min = models.CharField(max_length=25, blank=True, null=True)
    frac_max = models.CharField(max_length=9, blank=True, null=True)
    frac_min = models.CharField(max_length=9, blank=True, null=True)
    chron_age = models.CharField(max_length=20, blank=True, null=True)
    age_comm = models.TextField(blank=True, null=True)
    dms_lat = models.CharField(max_length=14, blank=True, null=True)
    dms_long = models.CharField(max_length=14, blank=True, null=True)
    dec_lat = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    dec_long = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    state = models.CharField(max_length=20, blank=True, null=True)
    county = models.CharField(max_length=20, blank=True, null=True)
    site_area = models.CharField(max_length=10, blank=True, null=True)
    gen_loc = models.CharField(max_length=1, blank=True, null=True)
    plate = models.CharField(max_length=12, blank=True, null=True)
    loc_detail = models.TextField(blank=True, null=True)
    lgroup = models.CharField(max_length=30, blank=True, null=True)
    formation = models.CharField(max_length=30, blank=True, null=True)
    member = models.CharField(max_length=30, blank=True, null=True)
    bed = models.CharField(max_length=30, blank=True, null=True)
    datum_plane = models.CharField(max_length=50, blank=True, null=True)
    tos = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    bos = models.DecimalField(max_digits=20, decimal_places=10, blank=True, null=True)
    rock_type = models.CharField(max_length=15, blank=True, null=True)
    rt_adj = models.CharField(max_length=20, blank=True, null=True)
    lith_comm = models.TextField(blank=True, null=True)
    sed_env_1 = models.CharField(max_length=15, blank=True, null=True)
    sed_env_2 = models.CharField(max_length=15, blank=True, null=True)
    event_circum = models.CharField(max_length=15, blank=True, null=True)
    se_comm = models.TextField(blank=True, null=True)
    climate_type = models.CharField(max_length=15, blank=True, null=True)
    biome = models.CharField(max_length=15, blank=True, null=True)
    v_ht = models.CharField(max_length=4, blank=True, null=True)
    v_struct = models.CharField(max_length=9, blank=True, null=True)
    v_envi_det = models.TextField(blank=True, null=True)
    disturb = models.CharField(max_length=16, blank=True, null=True)
    nutrients = models.CharField(max_length=7, blank=True, null=True)
    water = models.CharField(max_length=8, blank=True, null=True)
    seasonality = models.CharField(max_length=16, blank=True, null=True)
    seas_intens = models.CharField(max_length=3, blank=True, null=True)
    pri_prod = models.CharField(max_length=4, blank=True, null=True)
    moisture = models.CharField(max_length=12, blank=True, null=True)
    temperature = models.CharField(max_length=12, blank=True, null=True)
    assem_fm = models.CharField(max_length=12, blank=True, null=True)
    transport = models.CharField(max_length=20, blank=True, null=True)
    trans_mod = models.CharField(max_length=20, blank=True, null=True)
    weath_trmp = models.CharField(max_length=12, blank=True, null=True)
    pt_conc = models.CharField(max_length=20, blank=True, null=True)
    size_type = models.CharField(max_length=12, blank=True, null=True)
    vert_pres = models.CharField(max_length=12, blank=True, null=True)
    plant_pres = models.CharField(max_length=12, blank=True, null=True)
    invert_pres = models.CharField(max_length=12, blank=True, null=True)
    time_rep = models.CharField(max_length=12, blank=True, null=True)
    appr_num_spm = models.IntegerField(blank=True, null=True)
    num_spm = models.IntegerField(blank=True, null=True)
    true_quant = models.CharField(max_length=12, blank=True, null=True)
    complete = models.CharField(max_length=12, blank=True, null=True)
    num_quad = models.IntegerField(blank=True, null=True)
    taph_comm = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=12, blank=True, null=True)
